// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenImageFile():Promise<string>;

export function OpenVCardFile():Promise<Record<string, string>>;

export function SaveVCardFile(arg1:string,arg2:string):Promise<void>;
