// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenImageFile() {
  return window['go']['main']['App']['OpenImageFile']();
}

export function OpenSoundFile() {
  return window['go']['main']['App']['OpenSoundFile']();
}

export function OpenVCardFile() {
  return window['go']['main']['App']['OpenVCardFile']();
}

export function SaveVCardFile(arg1, arg2) {
  return window['go']['main']['App']['SaveVCardFile'](arg1, arg2);
}
