// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function GetWindowPosition() {
  return window['go']['main']['App']['GetWindowPosition']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenImageFile() {
  return window['go']['main']['App']['OpenImageFile']();
}

export function OpenSoundFile() {
  return window['go']['main']['App']['OpenSoundFile']();
}

export function OpenVCardFile() {
  return window['go']['main']['App']['OpenVCardFile']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveVCardFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveVCardFile'](arg1, arg2, arg3, arg4);
}

export function SetWindowPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetWindowPosition'](arg1, arg2, arg3, arg4);
}
