// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function ExportContact(arg1, arg2) {
  return window['go']['main']['App']['ExportContact'](arg1, arg2);
}

export function ExportToFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportToFile'](arg1, arg2, arg3);
}

export function ExportToFolder(arg1) {
  return window['go']['main']['App']['ExportToFolder'](arg1);
}

export function GetWindowPosition() {
  return window['go']['main']['App']['GetWindowPosition']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function NewVCardFile() {
  return window['go']['main']['App']['NewVCardFile']();
}

export function OpenImageFile() {
  return window['go']['main']['App']['OpenImageFile']();
}

export function OpenImportFiles() {
  return window['go']['main']['App']['OpenImportFiles']();
}

export function OpenSoundFile() {
  return window['go']['main']['App']['OpenSoundFile']();
}

export function OpenVCardFile() {
  return window['go']['main']['App']['OpenVCardFile']();
}

export function ReadFileContent(arg1) {
  return window['go']['main']['App']['ReadFileContent'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveContactPhoto(arg1, arg2) {
  return window['go']['main']['App']['SaveContactPhoto'](arg1, arg2);
}

export function SaveVCardFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveVCardFile'](arg1, arg2, arg3, arg4);
}

export function SetWindowPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetWindowPosition'](arg1, arg2, arg3, arg4);
}

export function WindowClose() {
  return window['go']['main']['App']['WindowClose']();
}

export function WindowMinimise() {
  return window['go']['main']['App']['WindowMinimise']();
}

export function WindowToggleMaximise() {
  return window['go']['main']['App']['WindowToggleMaximise']();
}
