// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseDirectory():Promise<string>;

export function ExportContact(arg1:string,arg2:string):Promise<void>;

export function ExportToFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportToFolder(arg1:Record<string, string>):Promise<void>;

export function GetWindowPosition():Promise<Record<string, number>>;

export function LoadConfig():Promise<main.AppConfig>;

export function NewVCardFile():Promise<Record<string, string>>;

export function OpenImageFile():Promise<string>;

export function OpenSoundFile():Promise<string>;

export function OpenVCardFile():Promise<Record<string, string>>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SaveContactPhoto(arg1:string,arg2:string):Promise<void>;

export function SaveVCardFile(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<void>;

export function SetWindowPosition(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function WindowClose():Promise<void>;

export function WindowMinimise():Promise<void>;

export function WindowToggleMaximise():Promise<void>;
